/* 
 * SCORM Cloud Rest API
 *
 * REST API used for SCORM Cloud integrations.
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace Com.RusticiSoftware.Cloud.V2.Model
{
    /// <summary>
    /// BatchTagsSchema
    /// </summary>
    [DataContract]
    public partial class BatchTagsSchema :  IEquatable<BatchTagsSchema>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BatchTagsSchema" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected BatchTagsSchema() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="BatchTagsSchema" /> class.
        /// </summary>
        /// <param name="Ids">Ids (required).</param>
        /// <param name="Tags">Tags (required).</param>
        public BatchTagsSchema(List<string> Ids = default(List<string>), List<string> Tags = default(List<string>))
        {
            // to ensure "Ids" is required (not null)
            if (Ids == null)
            {
                throw new InvalidDataException("Ids is a required property for BatchTagsSchema and cannot be null");
            }
            else
            {
                this.Ids = Ids;
            }
            // to ensure "Tags" is required (not null)
            if (Tags == null)
            {
                throw new InvalidDataException("Tags is a required property for BatchTagsSchema and cannot be null");
            }
            else
            {
                this.Tags = Tags;
            }
        }
        
        /// <summary>
        /// Gets or Sets Ids
        /// </summary>
        [DataMember(Name="ids", EmitDefaultValue=false)]
        public List<string> Ids { get; set; }
        /// <summary>
        /// Gets or Sets Tags
        /// </summary>
        [DataMember(Name="tags", EmitDefaultValue=false)]
        public List<string> Tags { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class BatchTagsSchema {\n");
            sb.Append("  Ids: ").Append(Ids).Append("\n");
            sb.Append("  Tags: ").Append(Tags).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as BatchTagsSchema);
        }

        /// <summary>
        /// Returns true if BatchTagsSchema instances are equal
        /// </summary>
        /// <param name="other">Instance of BatchTagsSchema to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(BatchTagsSchema other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.Ids == other.Ids ||
                    this.Ids != null &&
                    this.Ids.SequenceEqual(other.Ids)
                ) && 
                (
                    this.Tags == other.Tags ||
                    this.Tags != null &&
                    this.Tags.SequenceEqual(other.Tags)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.Ids != null)
                    hash = hash * 59 + this.Ids.GetHashCode();
                if (this.Tags != null)
                    hash = hash * 59 + this.Tags.GetHashCode();
                return hash;
            }
        }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        { 
            yield break;
        }
    }

}
