/* 
 * SCORM Cloud Rest API
 *
 * REST API used for SCORM Cloud integrations.
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = Com.RusticiSoftware.Cloud.V2.Client.SwaggerDateConverter;

namespace Com.RusticiSoftware.Cloud.V2.Model
{
    /// <summary>
    /// CourseListNonPagedSchema
    /// </summary>
    [DataContract]
    public partial class CourseListNonPagedSchema :  IEquatable<CourseListNonPagedSchema>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CourseListNonPagedSchema" /> class.
        /// </summary>
        /// <param name="courses">courses.</param>
        public CourseListNonPagedSchema(List<CourseSchema> courses = default(List<CourseSchema>))
        {
            this.Courses = courses;
        }
        
        /// <summary>
        /// Gets or Sets Courses
        /// </summary>
        [DataMember(Name="courses", EmitDefaultValue=false)]
        public List<CourseSchema> Courses { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CourseListNonPagedSchema {\n");
            sb.Append("  Courses: ").Append(Courses).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as CourseListNonPagedSchema);
        }

        /// <summary>
        /// Returns true if CourseListNonPagedSchema instances are equal
        /// </summary>
        /// <param name="input">Instance of CourseListNonPagedSchema to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CourseListNonPagedSchema input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Courses == input.Courses ||
                    this.Courses != null &&
                    this.Courses.SequenceEqual(input.Courses)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Courses != null)
                    hashCode = hashCode * 59 + this.Courses.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
