/* 
 * SCORM Cloud Rest API
 *
 * REST API used for SCORM Cloud integrations.
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = Com.RusticiSoftware.Cloud.V2.Client.SwaggerDateConverter;

namespace Com.RusticiSoftware.Cloud.V2.Model
{
    /// <summary>
    /// CourseActivitySchema
    /// </summary>
    [DataContract]
    public partial class CourseActivitySchema :  IEquatable<CourseActivitySchema>, IValidatableObject
    {
        /// <summary>
        /// The type of activity this is
        /// </summary>
        /// <value>The type of activity this is</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum ActivityTypeEnum
        {
            
            /// <summary>
            /// Enum UNKNOWN for value: UNKNOWN
            /// </summary>
            [EnumMember(Value = "UNKNOWN")]
            UNKNOWN = 1,
            
            /// <summary>
            /// Enum AGGREGATION for value: AGGREGATION
            /// </summary>
            [EnumMember(Value = "AGGREGATION")]
            AGGREGATION = 2,
            
            /// <summary>
            /// Enum SCO for value: SCO
            /// </summary>
            [EnumMember(Value = "SCO")]
            SCO = 3,
            
            /// <summary>
            /// Enum ASSET for value: ASSET
            /// </summary>
            [EnumMember(Value = "ASSET")]
            ASSET = 4,
            
            /// <summary>
            /// Enum OBJECTIVE for value: OBJECTIVE
            /// </summary>
            [EnumMember(Value = "OBJECTIVE")]
            OBJECTIVE = 5
        }

        /// <summary>
        /// The type of activity this is
        /// </summary>
        /// <value>The type of activity this is</value>
        [DataMember(Name="activityType", EmitDefaultValue=false)]
        public ActivityTypeEnum? ActivityType { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="CourseActivitySchema" /> class.
        /// </summary>
        /// <param name="externalIdentifier">An arbitrary identifier that the external LMS system can associate with this LearningObject to track it as it isreused across courses .</param>
        /// <param name="itemIdentifier">The string which identifies this activity in the context of its course.</param>
        /// <param name="resourceIdentifier">The string which identifies this activity&#39;s resource in a course&#39;s manifest.</param>
        /// <param name="activityType">The type of activity this is.</param>
        /// <param name="href">The web path used to launch this activity.</param>
        /// <param name="scaledPassingScore">The score required of a learner to pass this activity.</param>
        /// <param name="title">The title of the activity.</param>
        /// <param name="children">children.</param>
        public CourseActivitySchema(string externalIdentifier = default(string), string itemIdentifier = default(string), string resourceIdentifier = default(string), ActivityTypeEnum? activityType = default(ActivityTypeEnum?), string href = default(string), string scaledPassingScore = default(string), string title = default(string), List<CourseActivitySchema> children = default(List<CourseActivitySchema>))
        {
            this.ExternalIdentifier = externalIdentifier;
            this.ItemIdentifier = itemIdentifier;
            this.ResourceIdentifier = resourceIdentifier;
            this.ActivityType = activityType;
            this.Href = href;
            this.ScaledPassingScore = scaledPassingScore;
            this.Title = title;
            this.Children = children;
        }
        
        /// <summary>
        /// An arbitrary identifier that the external LMS system can associate with this LearningObject to track it as it isreused across courses 
        /// </summary>
        /// <value>An arbitrary identifier that the external LMS system can associate with this LearningObject to track it as it isreused across courses </value>
        [DataMember(Name="externalIdentifier", EmitDefaultValue=false)]
        public string ExternalIdentifier { get; set; }

        /// <summary>
        /// The string which identifies this activity in the context of its course
        /// </summary>
        /// <value>The string which identifies this activity in the context of its course</value>
        [DataMember(Name="itemIdentifier", EmitDefaultValue=false)]
        public string ItemIdentifier { get; set; }

        /// <summary>
        /// The string which identifies this activity&#39;s resource in a course&#39;s manifest
        /// </summary>
        /// <value>The string which identifies this activity&#39;s resource in a course&#39;s manifest</value>
        [DataMember(Name="resourceIdentifier", EmitDefaultValue=false)]
        public string ResourceIdentifier { get; set; }


        /// <summary>
        /// The web path used to launch this activity
        /// </summary>
        /// <value>The web path used to launch this activity</value>
        [DataMember(Name="href", EmitDefaultValue=false)]
        public string Href { get; set; }

        /// <summary>
        /// The score required of a learner to pass this activity
        /// </summary>
        /// <value>The score required of a learner to pass this activity</value>
        [DataMember(Name="scaledPassingScore", EmitDefaultValue=false)]
        public string ScaledPassingScore { get; set; }

        /// <summary>
        /// The title of the activity
        /// </summary>
        /// <value>The title of the activity</value>
        [DataMember(Name="title", EmitDefaultValue=false)]
        public string Title { get; set; }

        /// <summary>
        /// Gets or Sets Children
        /// </summary>
        [DataMember(Name="children", EmitDefaultValue=false)]
        public List<CourseActivitySchema> Children { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CourseActivitySchema {\n");
            sb.Append("  ExternalIdentifier: ").Append(ExternalIdentifier).Append("\n");
            sb.Append("  ItemIdentifier: ").Append(ItemIdentifier).Append("\n");
            sb.Append("  ResourceIdentifier: ").Append(ResourceIdentifier).Append("\n");
            sb.Append("  ActivityType: ").Append(ActivityType).Append("\n");
            sb.Append("  Href: ").Append(Href).Append("\n");
            sb.Append("  ScaledPassingScore: ").Append(ScaledPassingScore).Append("\n");
            sb.Append("  Title: ").Append(Title).Append("\n");
            sb.Append("  Children: ").Append(Children).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as CourseActivitySchema);
        }

        /// <summary>
        /// Returns true if CourseActivitySchema instances are equal
        /// </summary>
        /// <param name="input">Instance of CourseActivitySchema to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CourseActivitySchema input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.ExternalIdentifier == input.ExternalIdentifier ||
                    (this.ExternalIdentifier != null &&
                    this.ExternalIdentifier.Equals(input.ExternalIdentifier))
                ) && 
                (
                    this.ItemIdentifier == input.ItemIdentifier ||
                    (this.ItemIdentifier != null &&
                    this.ItemIdentifier.Equals(input.ItemIdentifier))
                ) && 
                (
                    this.ResourceIdentifier == input.ResourceIdentifier ||
                    (this.ResourceIdentifier != null &&
                    this.ResourceIdentifier.Equals(input.ResourceIdentifier))
                ) && 
                (
                    this.ActivityType == input.ActivityType ||
                    (this.ActivityType != null &&
                    this.ActivityType.Equals(input.ActivityType))
                ) && 
                (
                    this.Href == input.Href ||
                    (this.Href != null &&
                    this.Href.Equals(input.Href))
                ) && 
                (
                    this.ScaledPassingScore == input.ScaledPassingScore ||
                    (this.ScaledPassingScore != null &&
                    this.ScaledPassingScore.Equals(input.ScaledPassingScore))
                ) && 
                (
                    this.Title == input.Title ||
                    (this.Title != null &&
                    this.Title.Equals(input.Title))
                ) && 
                (
                    this.Children == input.Children ||
                    this.Children != null &&
                    this.Children.SequenceEqual(input.Children)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ExternalIdentifier != null)
                    hashCode = hashCode * 59 + this.ExternalIdentifier.GetHashCode();
                if (this.ItemIdentifier != null)
                    hashCode = hashCode * 59 + this.ItemIdentifier.GetHashCode();
                if (this.ResourceIdentifier != null)
                    hashCode = hashCode * 59 + this.ResourceIdentifier.GetHashCode();
                if (this.ActivityType != null)
                    hashCode = hashCode * 59 + this.ActivityType.GetHashCode();
                if (this.Href != null)
                    hashCode = hashCode * 59 + this.Href.GetHashCode();
                if (this.ScaledPassingScore != null)
                    hashCode = hashCode * 59 + this.ScaledPassingScore.GetHashCode();
                if (this.Title != null)
                    hashCode = hashCode * 59 + this.Title.GetHashCode();
                if (this.Children != null)
                    hashCode = hashCode * 59 + this.Children.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
