/* 
 * SCORM Cloud Rest API
 *
 * REST API used for SCORM Cloud integrations.
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace Com.RusticiSoftware.Cloud.V2.Model
{
    /// <summary>
    /// CredentialCreatedSchema
    /// </summary>
    [DataContract]
    public partial class CredentialCreatedSchema :  IEquatable<CredentialCreatedSchema>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CredentialCreatedSchema" /> class.
        /// </summary>
        /// <param name="Id">id for this credential.</param>
        /// <param name="Name">name for this credential.</param>
        /// <param name="Credential">The newly created API credential.</param>
        /// <param name="PensCredential">The PENS key for this credential.</param>
        /// <param name="Status">Status.</param>
        public CredentialCreatedSchema(string Id = default(string), string Name = default(string), string Credential = default(string), string PensCredential = default(string), string Status = default(string))
        {
            this.Id = Id;
            this.Name = Name;
            this.Credential = Credential;
            this.PensCredential = PensCredential;
            this.Status = Status;
        }
        
        /// <summary>
        /// id for this credential
        /// </summary>
        /// <value>id for this credential</value>
        [DataMember(Name="id", EmitDefaultValue=false)]
        public string Id { get; set; }
        /// <summary>
        /// name for this credential
        /// </summary>
        /// <value>name for this credential</value>
        [DataMember(Name="name", EmitDefaultValue=false)]
        public string Name { get; set; }
        /// <summary>
        /// The newly created API credential
        /// </summary>
        /// <value>The newly created API credential</value>
        [DataMember(Name="credential", EmitDefaultValue=false)]
        public string Credential { get; set; }
        /// <summary>
        /// The PENS key for this credential
        /// </summary>
        /// <value>The PENS key for this credential</value>
        [DataMember(Name="pensCredential", EmitDefaultValue=false)]
        public string PensCredential { get; set; }
        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [DataMember(Name="status", EmitDefaultValue=false)]
        public string Status { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CredentialCreatedSchema {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Credential: ").Append(Credential).Append("\n");
            sb.Append("  PensCredential: ").Append(PensCredential).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as CredentialCreatedSchema);
        }

        /// <summary>
        /// Returns true if CredentialCreatedSchema instances are equal
        /// </summary>
        /// <param name="other">Instance of CredentialCreatedSchema to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CredentialCreatedSchema other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.Id == other.Id ||
                    this.Id != null &&
                    this.Id.Equals(other.Id)
                ) && 
                (
                    this.Name == other.Name ||
                    this.Name != null &&
                    this.Name.Equals(other.Name)
                ) && 
                (
                    this.Credential == other.Credential ||
                    this.Credential != null &&
                    this.Credential.Equals(other.Credential)
                ) && 
                (
                    this.PensCredential == other.PensCredential ||
                    this.PensCredential != null &&
                    this.PensCredential.Equals(other.PensCredential)
                ) && 
                (
                    this.Status == other.Status ||
                    this.Status != null &&
                    this.Status.Equals(other.Status)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.Id != null)
                    hash = hash * 59 + this.Id.GetHashCode();
                if (this.Name != null)
                    hash = hash * 59 + this.Name.GetHashCode();
                if (this.Credential != null)
                    hash = hash * 59 + this.Credential.GetHashCode();
                if (this.PensCredential != null)
                    hash = hash * 59 + this.PensCredential.GetHashCode();
                if (this.Status != null)
                    hash = hash * 59 + this.Status.GetHashCode();
                return hash;
            }
        }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        { 
            yield break;
        }
    }

}
