/* 
 * SCORM Cloud Rest API
 *
 * REST API used for SCORM Cloud integrations.
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace Com.RusticiSoftware.Cloud.V2.Model
{
    /// <summary>
    /// LaunchLinkRequestSchema
    /// </summary>
    [DataContract]
    public partial class LaunchLinkRequestSchema :  IEquatable<LaunchLinkRequestSchema>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="LaunchLinkRequestSchema" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected LaunchLinkRequestSchema() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="LaunchLinkRequestSchema" /> class.
        /// </summary>
        /// <param name="Expiry">Number of seconds from now this link will expire in. Defaults to 120s. Range 10s:300s (default to 120).</param>
        /// <param name="RedirectOnExitUrl">The URL the application should redirect to when the learner exits a course. If not specified, configured value will be used. (required).</param>
        /// <param name="Tracking">Should this launch be tracked? If false, Engine will avoid tracking to the extent possible for the standard being used. (default to true).</param>
        /// <param name="StartSco">For SCORM, SCO identifier to override launch, overriding the normal sequencing..</param>
        /// <param name="Culture">This parameter should specify a culture code. If specified, and supported, the navigation and alerts in the player will be displayed in the associated language. If not specified, the locale of the user’s browser will be used..</param>
        /// <param name="CssUrl">A Url pointing to custom css for the player to use..</param>
        /// <param name="LearnerTags">LearnerTags.</param>
        /// <param name="CourseTags">CourseTags.</param>
        /// <param name="RegistrationTags">RegistrationTags.</param>
        /// <param name="Additionalvalues">Additionalvalues.</param>
        public LaunchLinkRequestSchema(int? Expiry = 120, string RedirectOnExitUrl = default(string), bool? Tracking = true, string StartSco = default(string), string Culture = default(string), string CssUrl = default(string), List<string> LearnerTags = default(List<string>), List<string> CourseTags = default(List<string>), List<string> RegistrationTags = default(List<string>), List<ItemValuePairSchema> Additionalvalues = default(List<ItemValuePairSchema>))
        {
            // to ensure "RedirectOnExitUrl" is required (not null)
            if (RedirectOnExitUrl == null)
            {
                throw new InvalidDataException("RedirectOnExitUrl is a required property for LaunchLinkRequestSchema and cannot be null");
            }
            else
            {
                this.RedirectOnExitUrl = RedirectOnExitUrl;
            }
            // use default value if no "Expiry" provided
            if (Expiry == null)
            {
                this.Expiry = 120;
            }
            else
            {
                this.Expiry = Expiry;
            }
            // use default value if no "Tracking" provided
            if (Tracking == null)
            {
                this.Tracking = true;
            }
            else
            {
                this.Tracking = Tracking;
            }
            this.StartSco = StartSco;
            this.Culture = Culture;
            this.CssUrl = CssUrl;
            this.LearnerTags = LearnerTags;
            this.CourseTags = CourseTags;
            this.RegistrationTags = RegistrationTags;
            this.Additionalvalues = Additionalvalues;
        }
        
        /// <summary>
        /// Number of seconds from now this link will expire in. Defaults to 120s. Range 10s:300s
        /// </summary>
        /// <value>Number of seconds from now this link will expire in. Defaults to 120s. Range 10s:300s</value>
        [DataMember(Name="expiry", EmitDefaultValue=false)]
        public int? Expiry { get; set; }
        /// <summary>
        /// The URL the application should redirect to when the learner exits a course. If not specified, configured value will be used.
        /// </summary>
        /// <value>The URL the application should redirect to when the learner exits a course. If not specified, configured value will be used.</value>
        [DataMember(Name="redirectOnExitUrl", EmitDefaultValue=false)]
        public string RedirectOnExitUrl { get; set; }
        /// <summary>
        /// Should this launch be tracked? If false, Engine will avoid tracking to the extent possible for the standard being used.
        /// </summary>
        /// <value>Should this launch be tracked? If false, Engine will avoid tracking to the extent possible for the standard being used.</value>
        [DataMember(Name="tracking", EmitDefaultValue=false)]
        public bool? Tracking { get; set; }
        /// <summary>
        /// For SCORM, SCO identifier to override launch, overriding the normal sequencing.
        /// </summary>
        /// <value>For SCORM, SCO identifier to override launch, overriding the normal sequencing.</value>
        [DataMember(Name="startSco", EmitDefaultValue=false)]
        public string StartSco { get; set; }
        /// <summary>
        /// This parameter should specify a culture code. If specified, and supported, the navigation and alerts in the player will be displayed in the associated language. If not specified, the locale of the user’s browser will be used.
        /// </summary>
        /// <value>This parameter should specify a culture code. If specified, and supported, the navigation and alerts in the player will be displayed in the associated language. If not specified, the locale of the user’s browser will be used.</value>
        [DataMember(Name="culture", EmitDefaultValue=false)]
        public string Culture { get; set; }
        /// <summary>
        /// A Url pointing to custom css for the player to use.
        /// </summary>
        /// <value>A Url pointing to custom css for the player to use.</value>
        [DataMember(Name="cssUrl", EmitDefaultValue=false)]
        public string CssUrl { get; set; }
        /// <summary>
        /// Gets or Sets LearnerTags
        /// </summary>
        [DataMember(Name="learnerTags", EmitDefaultValue=false)]
        public List<string> LearnerTags { get; set; }
        /// <summary>
        /// Gets or Sets CourseTags
        /// </summary>
        [DataMember(Name="courseTags", EmitDefaultValue=false)]
        public List<string> CourseTags { get; set; }
        /// <summary>
        /// Gets or Sets RegistrationTags
        /// </summary>
        [DataMember(Name="registrationTags", EmitDefaultValue=false)]
        public List<string> RegistrationTags { get; set; }
        /// <summary>
        /// Gets or Sets Additionalvalues
        /// </summary>
        [DataMember(Name="additionalvalues", EmitDefaultValue=false)]
        public List<ItemValuePairSchema> Additionalvalues { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class LaunchLinkRequestSchema {\n");
            sb.Append("  Expiry: ").Append(Expiry).Append("\n");
            sb.Append("  RedirectOnExitUrl: ").Append(RedirectOnExitUrl).Append("\n");
            sb.Append("  Tracking: ").Append(Tracking).Append("\n");
            sb.Append("  StartSco: ").Append(StartSco).Append("\n");
            sb.Append("  Culture: ").Append(Culture).Append("\n");
            sb.Append("  CssUrl: ").Append(CssUrl).Append("\n");
            sb.Append("  LearnerTags: ").Append(LearnerTags).Append("\n");
            sb.Append("  CourseTags: ").Append(CourseTags).Append("\n");
            sb.Append("  RegistrationTags: ").Append(RegistrationTags).Append("\n");
            sb.Append("  Additionalvalues: ").Append(Additionalvalues).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as LaunchLinkRequestSchema);
        }

        /// <summary>
        /// Returns true if LaunchLinkRequestSchema instances are equal
        /// </summary>
        /// <param name="other">Instance of LaunchLinkRequestSchema to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(LaunchLinkRequestSchema other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.Expiry == other.Expiry ||
                    this.Expiry != null &&
                    this.Expiry.Equals(other.Expiry)
                ) && 
                (
                    this.RedirectOnExitUrl == other.RedirectOnExitUrl ||
                    this.RedirectOnExitUrl != null &&
                    this.RedirectOnExitUrl.Equals(other.RedirectOnExitUrl)
                ) && 
                (
                    this.Tracking == other.Tracking ||
                    this.Tracking != null &&
                    this.Tracking.Equals(other.Tracking)
                ) && 
                (
                    this.StartSco == other.StartSco ||
                    this.StartSco != null &&
                    this.StartSco.Equals(other.StartSco)
                ) && 
                (
                    this.Culture == other.Culture ||
                    this.Culture != null &&
                    this.Culture.Equals(other.Culture)
                ) && 
                (
                    this.CssUrl == other.CssUrl ||
                    this.CssUrl != null &&
                    this.CssUrl.Equals(other.CssUrl)
                ) && 
                (
                    this.LearnerTags == other.LearnerTags ||
                    this.LearnerTags != null &&
                    this.LearnerTags.SequenceEqual(other.LearnerTags)
                ) && 
                (
                    this.CourseTags == other.CourseTags ||
                    this.CourseTags != null &&
                    this.CourseTags.SequenceEqual(other.CourseTags)
                ) && 
                (
                    this.RegistrationTags == other.RegistrationTags ||
                    this.RegistrationTags != null &&
                    this.RegistrationTags.SequenceEqual(other.RegistrationTags)
                ) && 
                (
                    this.Additionalvalues == other.Additionalvalues ||
                    this.Additionalvalues != null &&
                    this.Additionalvalues.SequenceEqual(other.Additionalvalues)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.Expiry != null)
                    hash = hash * 59 + this.Expiry.GetHashCode();
                if (this.RedirectOnExitUrl != null)
                    hash = hash * 59 + this.RedirectOnExitUrl.GetHashCode();
                if (this.Tracking != null)
                    hash = hash * 59 + this.Tracking.GetHashCode();
                if (this.StartSco != null)
                    hash = hash * 59 + this.StartSco.GetHashCode();
                if (this.Culture != null)
                    hash = hash * 59 + this.Culture.GetHashCode();
                if (this.CssUrl != null)
                    hash = hash * 59 + this.CssUrl.GetHashCode();
                if (this.LearnerTags != null)
                    hash = hash * 59 + this.LearnerTags.GetHashCode();
                if (this.CourseTags != null)
                    hash = hash * 59 + this.CourseTags.GetHashCode();
                if (this.RegistrationTags != null)
                    hash = hash * 59 + this.RegistrationTags.GetHashCode();
                if (this.Additionalvalues != null)
                    hash = hash * 59 + this.Additionalvalues.GetHashCode();
                return hash;
            }
        }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        { 
            yield break;
        }
    }

}
