/* 
 * SCORM Cloud Rest API
 *
 * REST API used for SCORM Cloud integrations.
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = Com.RusticiSoftware.Cloud.V2.Client.SwaggerDateConverter;

namespace Com.RusticiSoftware.Cloud.V2.Model
{
    /// <summary>
    /// PingSchema
    /// </summary>
    [DataContract]
    public partial class PingSchema :  IEquatable<PingSchema>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PingSchema" /> class.
        /// </summary>
        /// <param name="apiMessage">apiMessage.</param>
        /// <param name="currentTime">currentTime.</param>
        public PingSchema(string apiMessage = default(string), string currentTime = default(string))
        {
            this.ApiMessage = apiMessage;
            this.CurrentTime = currentTime;
        }
        
        /// <summary>
        /// Gets or Sets ApiMessage
        /// </summary>
        [DataMember(Name="apiMessage", EmitDefaultValue=false)]
        public string ApiMessage { get; set; }

        /// <summary>
        /// Gets or Sets CurrentTime
        /// </summary>
        [DataMember(Name="currentTime", EmitDefaultValue=false)]
        public string CurrentTime { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class PingSchema {\n");
            sb.Append("  ApiMessage: ").Append(ApiMessage).Append("\n");
            sb.Append("  CurrentTime: ").Append(CurrentTime).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as PingSchema);
        }

        /// <summary>
        /// Returns true if PingSchema instances are equal
        /// </summary>
        /// <param name="input">Instance of PingSchema to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PingSchema input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.ApiMessage == input.ApiMessage ||
                    (this.ApiMessage != null &&
                    this.ApiMessage.Equals(input.ApiMessage))
                ) && 
                (
                    this.CurrentTime == input.CurrentTime ||
                    (this.CurrentTime != null &&
                    this.CurrentTime.Equals(input.CurrentTime))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ApiMessage != null)
                    hashCode = hashCode * 59 + this.ApiMessage.GetHashCode();
                if (this.CurrentTime != null)
                    hashCode = hashCode * 59 + this.CurrentTime.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
