/* 
 * SCORM Cloud Rest API
 *
 * REST API used for SCORM Cloud integrations.
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace Com.RusticiSoftware.Cloud.V2.Model
{
    /// <summary>
    /// PublicInvitationList
    /// </summary>
    [DataContract]
    public partial class PublicInvitationList :  IEquatable<PublicInvitationList>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PublicInvitationList" /> class.
        /// </summary>
        /// <param name="Invitations">A list of public invitation objects..</param>
        /// <param name="More">More.</param>
        public PublicInvitationList(List<PublicInvitationSchema> Invitations = default(List<PublicInvitationSchema>), string More = default(string))
        {
            this.Invitations = Invitations;
            this.More = More;
        }
        
        /// <summary>
        /// A list of public invitation objects.
        /// </summary>
        /// <value>A list of public invitation objects.</value>
        [DataMember(Name="invitations", EmitDefaultValue=false)]
        public List<PublicInvitationSchema> Invitations { get; set; }
        /// <summary>
        /// Gets or Sets More
        /// </summary>
        [DataMember(Name="more", EmitDefaultValue=false)]
        public string More { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class PublicInvitationList {\n");
            sb.Append("  Invitations: ").Append(Invitations).Append("\n");
            sb.Append("  More: ").Append(More).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as PublicInvitationList);
        }

        /// <summary>
        /// Returns true if PublicInvitationList instances are equal
        /// </summary>
        /// <param name="other">Instance of PublicInvitationList to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PublicInvitationList other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.Invitations == other.Invitations ||
                    this.Invitations != null &&
                    this.Invitations.SequenceEqual(other.Invitations)
                ) && 
                (
                    this.More == other.More ||
                    this.More != null &&
                    this.More.Equals(other.More)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.Invitations != null)
                    hash = hash * 59 + this.Invitations.GetHashCode();
                if (this.More != null)
                    hash = hash * 59 + this.More.GetHashCode();
                return hash;
            }
        }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        { 
            yield break;
        }
    }

}
