/* 
 * SCORM Cloud Rest API
 *
 * REST API used for SCORM Cloud integrations.
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = Com.RusticiSoftware.Cloud.V2.Client.SwaggerDateConverter;

namespace Com.RusticiSoftware.Cloud.V2.Model
{
    /// <summary>
    /// SettingValidValue
    /// </summary>
    [DataContract]
    public partial class SettingValidValue :  IEquatable<SettingValidValue>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SettingValidValue" /> class.
        /// </summary>
        /// <param name="value">value.</param>
        /// <param name="valueDescription">Description of what this valid value means, how it will be applied if used in a setting.</param>
        public SettingValidValue(string value = default(string), string valueDescription = default(string))
        {
            this.Value = value;
            this.ValueDescription = valueDescription;
        }
        
        /// <summary>
        /// Gets or Sets Value
        /// </summary>
        [DataMember(Name="value", EmitDefaultValue=false)]
        public string Value { get; set; }

        /// <summary>
        /// Description of what this valid value means, how it will be applied if used in a setting
        /// </summary>
        /// <value>Description of what this valid value means, how it will be applied if used in a setting</value>
        [DataMember(Name="valueDescription", EmitDefaultValue=false)]
        public string ValueDescription { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class SettingValidValue {\n");
            sb.Append("  Value: ").Append(Value).Append("\n");
            sb.Append("  ValueDescription: ").Append(ValueDescription).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as SettingValidValue);
        }

        /// <summary>
        /// Returns true if SettingValidValue instances are equal
        /// </summary>
        /// <param name="input">Instance of SettingValidValue to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SettingValidValue input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Value == input.Value ||
                    (this.Value != null &&
                    this.Value.Equals(input.Value))
                ) && 
                (
                    this.ValueDescription == input.ValueDescription ||
                    (this.ValueDescription != null &&
                    this.ValueDescription.Equals(input.ValueDescription))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Value != null)
                    hashCode = hashCode * 59 + this.Value.GetHashCode();
                if (this.ValueDescription != null)
                    hashCode = hashCode * 59 + this.ValueDescription.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
