/* 
 * SCORM Cloud Rest API
 *
 * REST API used for SCORM Cloud integrations.
 *
 * OpenAPI spec version: 2.0 beta
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace Com.RusticiSoftware.Cloud.V2.Model
{
    /// <summary>
    /// TokenRequestSchema
    /// </summary>
    [DataContract]
    public partial class TokenRequestSchema :  IEquatable<TokenRequestSchema>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TokenRequestSchema" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected TokenRequestSchema() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="TokenRequestSchema" /> class.
        /// </summary>
        /// <param name="Permissions">Permissions (required).</param>
        /// <param name="Expiry">Expiration of the token. This should not be set far in the future, as there is no way to invalidate an individual token. (required).</param>
        public TokenRequestSchema(PermissionsSchema Permissions = null, DateTime? Expiry = null)
        {
            // to ensure "Permissions" is required (not null)
            if (Permissions == null)
            {
                throw new InvalidDataException("Permissions is a required property for TokenRequestSchema and cannot be null");
            }
            else
            {
                this.Permissions = Permissions;
            }
            // to ensure "Expiry" is required (not null)
            if (Expiry == null)
            {
                throw new InvalidDataException("Expiry is a required property for TokenRequestSchema and cannot be null");
            }
            else
            {
                this.Expiry = Expiry;
            }
        }
        
        /// <summary>
        /// Gets or Sets Permissions
        /// </summary>
        [DataMember(Name="permissions", EmitDefaultValue=false)]
        public PermissionsSchema Permissions { get; set; }
        /// <summary>
        /// Expiration of the token. This should not be set far in the future, as there is no way to invalidate an individual token.
        /// </summary>
        /// <value>Expiration of the token. This should not be set far in the future, as there is no way to invalidate an individual token.</value>
        [DataMember(Name="expiry", EmitDefaultValue=false)]
        public DateTime? Expiry { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class TokenRequestSchema {\n");
            sb.Append("  Permissions: ").Append(Permissions).Append("\n");
            sb.Append("  Expiry: ").Append(Expiry).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as TokenRequestSchema);
        }

        /// <summary>
        /// Returns true if TokenRequestSchema instances are equal
        /// </summary>
        /// <param name="other">Instance of TokenRequestSchema to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TokenRequestSchema other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.Permissions == other.Permissions ||
                    this.Permissions != null &&
                    this.Permissions.Equals(other.Permissions)
                ) && 
                (
                    this.Expiry == other.Expiry ||
                    this.Expiry != null &&
                    this.Expiry.Equals(other.Expiry)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.Permissions != null)
                    hash = hash * 59 + this.Permissions.GetHashCode();
                if (this.Expiry != null)
                    hash = hash * 59 + this.Expiry.GetHashCode();
                return hash;
            }
        }
    }

}
