/* 
 * SCORM Cloud Rest API
 *
 * REST API used for SCORM Cloud integrations.
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = Com.RusticiSoftware.Cloud.V2.Client.SwaggerDateConverter;

namespace Com.RusticiSoftware.Cloud.V2.Model
{
    /// <summary>
    /// https://github.com/adlnet/xAPI-Spec/blob/1.0.2/xAPI.md#42-retrieval-of-statements
    /// </summary>
    [DataContract]
    public partial class XapiStatementResult :  IEquatable<XapiStatementResult>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="XapiStatementResult" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected XapiStatementResult() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="XapiStatementResult" /> class.
        /// </summary>
        /// <param name="statements">statements (required).</param>
        /// <param name="more">more.</param>
        public XapiStatementResult(List<XapiStatement> statements = default(List<XapiStatement>), string more = default(string))
        {
            // to ensure "statements" is required (not null)
            if (statements == null)
            {
                throw new InvalidDataException("statements is a required property for XapiStatementResult and cannot be null");
            }
            else
            {
                this.Statements = statements;
            }
            this.More = more;
        }
        
        /// <summary>
        /// Gets or Sets Statements
        /// </summary>
        [DataMember(Name="statements", EmitDefaultValue=false)]
        public List<XapiStatement> Statements { get; set; }

        /// <summary>
        /// Gets or Sets More
        /// </summary>
        [DataMember(Name="more", EmitDefaultValue=false)]
        public string More { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class XapiStatementResult {\n");
            sb.Append("  Statements: ").Append(Statements).Append("\n");
            sb.Append("  More: ").Append(More).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as XapiStatementResult);
        }

        /// <summary>
        /// Returns true if XapiStatementResult instances are equal
        /// </summary>
        /// <param name="input">Instance of XapiStatementResult to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(XapiStatementResult input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Statements == input.Statements ||
                    this.Statements != null &&
                    this.Statements.SequenceEqual(input.Statements)
                ) && 
                (
                    this.More == input.More ||
                    (this.More != null &&
                    this.More.Equals(input.More))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Statements != null)
                    hashCode = hashCode * 59 + this.Statements.GetHashCode();
                if (this.More != null)
                    hashCode = hashCode * 59 + this.More.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
