/* 
 * SCORM Cloud Rest API
 *
 * REST API used for SCORM Cloud integrations.
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = Com.RusticiSoftware.Cloud.V2.Client.SwaggerDateConverter;

namespace Com.RusticiSoftware.Cloud.V2.Model
{
    /// <summary>
    /// https://github.com/adlnet/xAPI-Spec/blob/1.0.2/xAPI.md#4124-account-object
    /// </summary>
    [DataContract]
    public partial class XapiAccount :  IEquatable<XapiAccount>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="XapiAccount" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected XapiAccount() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="XapiAccount" /> class.
        /// </summary>
        /// <param name="homePage">homePage (required).</param>
        /// <param name="name">name (required).</param>
        public XapiAccount(string homePage = default(string), string name = default(string))
        {
            // to ensure "homePage" is required (not null)
            if (homePage == null)
            {
                throw new InvalidDataException("homePage is a required property for XapiAccount and cannot be null");
            }
            else
            {
                this.HomePage = homePage;
            }
            // to ensure "name" is required (not null)
            if (name == null)
            {
                throw new InvalidDataException("name is a required property for XapiAccount and cannot be null");
            }
            else
            {
                this.Name = name;
            }
        }
        
        /// <summary>
        /// Gets or Sets HomePage
        /// </summary>
        [DataMember(Name="homePage", EmitDefaultValue=false)]
        public string HomePage { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name="name", EmitDefaultValue=false)]
        public string Name { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class XapiAccount {\n");
            sb.Append("  HomePage: ").Append(HomePage).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as XapiAccount);
        }

        /// <summary>
        /// Returns true if XapiAccount instances are equal
        /// </summary>
        /// <param name="input">Instance of XapiAccount to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(XapiAccount input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.HomePage == input.HomePage ||
                    (this.HomePage != null &&
                    this.HomePage.Equals(input.HomePage))
                ) && 
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.HomePage != null)
                    hashCode = hashCode * 59 + this.HomePage.GetHashCode();
                if (this.Name != null)
                    hashCode = hashCode * 59 + this.Name.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
