/* 
 * SCORM Cloud Rest API
 *
 * REST API used for SCORM Cloud integrations.
 *
 * OpenAPI spec version: 2.0 beta
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Com.RusticiSoftware.Cloud.V2.Api;
using Com.RusticiSoftware.Cloud.V2.Model;
using Com.RusticiSoftware.Cloud.V2.Client;
using System.Reflection;

namespace Com.RusticiSoftware.Cloud.V2.Test
{
    /// <summary>
    ///  Class for testing LaunchHistorySchema
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class LaunchHistorySchemaTests
    {
        // TODO uncomment below to declare an instance variable for LaunchHistorySchema
        //private LaunchHistorySchema instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of LaunchHistorySchema
            //instance = new LaunchHistorySchema();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of LaunchHistorySchema
        /// </summary>
        [Test]
        public void LaunchHistorySchemaInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" LaunchHistorySchema
            //Assert.IsInstanceOfType<LaunchHistorySchema> (instance, "variable 'instance' is a LaunchHistorySchema");
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Instance'
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO unit test for the property 'Instance'
        }
        /// <summary>
        /// Test the property 'Score'
        /// </summary>
        [Test]
        public void ScoreTest()
        {
            // TODO unit test for the property 'Score'
        }
        /// <summary>
        /// Test the property 'CompletionStatus'
        /// </summary>
        [Test]
        public void CompletionStatusTest()
        {
            // TODO unit test for the property 'CompletionStatus'
        }
        /// <summary>
        /// Test the property 'SuccessStatus'
        /// </summary>
        [Test]
        public void SuccessStatusTest()
        {
            // TODO unit test for the property 'SuccessStatus'
        }
        /// <summary>
        /// Test the property 'HistoryLog'
        /// </summary>
        [Test]
        public void HistoryLogTest()
        {
            // TODO unit test for the property 'HistoryLog'
        }
        /// <summary>
        /// Test the property 'TotalSecondsTracked'
        /// </summary>
        [Test]
        public void TotalSecondsTrackedTest()
        {
            // TODO unit test for the property 'TotalSecondsTracked'
        }
        /// <summary>
        /// Test the property 'LaunchTime'
        /// </summary>
        [Test]
        public void LaunchTimeTest()
        {
            // TODO unit test for the property 'LaunchTime'
        }
        /// <summary>
        /// Test the property 'ExitTime'
        /// </summary>
        [Test]
        public void ExitTimeTest()
        {
            // TODO unit test for the property 'ExitTime'
        }
        /// <summary>
        /// Test the property 'LastRuntimeUpdate'
        /// </summary>
        [Test]
        public void LastRuntimeUpdateTest()
        {
            // TODO unit test for the property 'LastRuntimeUpdate'
        }

    }

}
