/* 
 * SCORM Cloud Rest API
 *
 * REST API used for SCORM Cloud integrations.
 *
 * OpenAPI spec version: 2.0 beta
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Com.RusticiSoftware.Cloud.V2.Api;
using Com.RusticiSoftware.Cloud.V2.Model;
using Com.RusticiSoftware.Cloud.V2.Client;
using System.Reflection;

namespace Com.RusticiSoftware.Cloud.V2.Test
{
    /// <summary>
    ///  Class for testing SettingMetadata
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SettingMetadataTests
    {
        // TODO uncomment below to declare an instance variable for SettingMetadata
        //private SettingMetadata instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SettingMetadata
            //instance = new SettingMetadata();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SettingMetadata
        /// </summary>
        [Test]
        public void SettingMetadataInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SettingMetadata
            //Assert.IsInstanceOfType<SettingMetadata> (instance, "variable 'instance' is a SettingMetadata");
        }

        /// <summary>
        /// Test the property '_Default'
        /// </summary>
        [Test]
        public void _DefaultTest()
        {
            // TODO unit test for the property '_Default'
        }
        /// <summary>
        /// Test the property 'DataType'
        /// </summary>
        [Test]
        public void DataTypeTest()
        {
            // TODO unit test for the property 'DataType'
        }
        /// <summary>
        /// Test the property 'SettingDescription'
        /// </summary>
        [Test]
        public void SettingDescriptionTest()
        {
            // TODO unit test for the property 'SettingDescription'
        }
        /// <summary>
        /// Test the property 'Level'
        /// </summary>
        [Test]
        public void LevelTest()
        {
            // TODO unit test for the property 'Level'
        }
        /// <summary>
        /// Test the property 'LearningStandards'
        /// </summary>
        [Test]
        public void LearningStandardsTest()
        {
            // TODO unit test for the property 'LearningStandards'
        }
        /// <summary>
        /// Test the property 'LearningStandardVariant'
        /// </summary>
        [Test]
        public void LearningStandardVariantTest()
        {
            // TODO unit test for the property 'LearningStandardVariant'
        }
        /// <summary>
        /// Test the property 'Fallback'
        /// </summary>
        [Test]
        public void FallbackTest()
        {
            // TODO unit test for the property 'Fallback'
        }
        /// <summary>
        /// Test the property 'ValidValues'
        /// </summary>
        [Test]
        public void ValidValuesTest()
        {
            // TODO unit test for the property 'ValidValues'
        }

    }

}
